//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naiva.Areas.WorkExperience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public System.Guid Id { get; set; }
        public System.DateTime Date1 { get; set; }
        public string Date2 { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
    }
}
